Db dump
future-stardust/url-shrtnr-le-gushqua pull request #17
Opened 2021-03-10 22:24 UTC by quppeq

Функціонал бекапу і відновлення данних

2021-03-10 22:27 UTC, quppeq commented
Історично склалось, що реалізація Авторизації почала окремо реалізацію БД
Тому я продовжив з тієї гілки

2021-03-11 18:36 UTC, Jusarine requested changes

2021-03-11 18:36 UTC, Jusarine commented on src/main/java/edu/kpi/testcourse/bigtable/AliasDaoImpl.java
> +    HashMap<String, Alias> aliasMap = Main.getGson().fromJson(aliasJson, HashMap.class);
Please use polymorphism i.e. use Map<String, Alias> aliasMap = ...
Thus we can easily change it to another implementation if we need.

2021-03-11 18:36 UTC, Jusarine commented on src/test/java/edu/kpi/testcourse/bigtable/SerializibleImplTest.java
> +    AliasDaoImpl dao = new AliasDaoImpl();
Here is also better to use polymorphism

2021-03-11 18:36 UTC, Jusarine commented on src/test/java/edu/kpi/testcourse/bigtable/SerializibleImplTest.java
> +    assertThat(json).isEqualTo("{\"shrt\":"
Let's use multiline strings, it's available from java 13.
"""
test
test
...
"""

2021-03-11 18:41 UTC, Jusarine commented on src/main/java/edu/kpi/testcourse/bigtable/BigTableManager.java
> +      for (Serializible dao : daos) {
Good work:)

2021-03-11 18:46 UTC, quppeq commented on src/test/java/edu/kpi/testcourse/bigtable/SerializibleImplTest.java
> +    AliasDaoImpl dao = new AliasDaoImpl();
it`s not pure "serializible" test, because we use methods like "add", "put", etc

2021-03-11 18:46 UTC, quppeq commented on src/test/java/edu/kpi/testcourse/bigtable/SerializibleImplTest.java
> +    AliasDaoImpl dao = new AliasDaoImpl();
and we test our realization, yes

2021-03-11 18:54 UTC, Jusarine commented on src/test/java/edu/kpi/testcourse/bigtable/SerializibleImplTest.java
> +    AliasDaoImpl dao = new AliasDaoImpl();
I mean to use AliasDao

2021-03-11 18:56 UTC, quppeq commented on src/test/java/edu/kpi/testcourse/bigtable/SerializibleImplTest.java
> +    AliasDaoImpl dao = new AliasDaoImpl();
damn.
Thanks)

2021-03-11 21:57 UTC, Jusarine approved these changes
All ok

2021-03-11 21:58 UTC, merged